import java.util.HashMap;
import java.util.Map.Entry;

/*

389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/


public class FindTheDifference {
	
	public char findTheDifference(String s, String t) {
		char[] sChars = s.toCharArray();
		char[] tChars = t.toCharArray();

		HashMap<Character, Integer> map = new HashMap<Character, Integer>();

		for (int i = 0; i < tChars.length; i++) {
			int value;
			if (map.containsKey(tChars[i])) {
				value = map.get(tChars[i]) + 1;
			} else {
				value = 1;
			}
			map.put(tChars[i], value);
		}

		for (int i = 0; i < sChars.length; i++) {
			if (map.containsKey(sChars[i])) {
				map.put(sChars[i], map.get(sChars[i]) - 1);
			}
		}

		for (Character c : map.keySet()) {
			if (map.get(c) != 0) {
				return c;
			}
		}
		return '0';
		
		//a better solution
		/*int x= 0;
	    
	    for(int i=0; i<s.length();i++){
	        x= x ^ s.charAt(i);
	    }
	    
	    for(int i = 0; i<t.length(); i++){
	        x= x ^ t.charAt(i);
	    }
	    
	    return (char) x;*/


	}

}
