import java.util.HashMap;
import java.util.Map.Entry;

/*

389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/


public class FindTheDifference {
	
	public char findTheDifference(String s, String t) {
		char[] sChars = s.toCharArray();
		char[] tChars = t.toCharArray();

		HashMap<Character, Integer> sMap = new HashMap<Character, Integer>();
		HashMap<Character, Integer> tMap = new HashMap<Character, Integer>();
		for (int i = 0; i < sChars.length; i++) {
			int value;
			if (sMap.containsKey(sChars[i])) {
				value = sMap.get(sChars[i]) + 1;
			} else {
				value = 1;
			}
			sMap.put(sChars[i], value);
		}
		
		for (int i = 0; i < tChars.length; i++) {
			int value;
			if (tMap.containsKey(tChars[i])) {
				value = tMap.get(tChars[i]) + 1;
			} else {
				value = 1;
			}
			tMap.put(tChars[i], value);
		}

		for (Entry<Character, Integer> tEntry : tMap.entrySet()) {
			Character tCharacter = tEntry.getKey();
			Integer tInt = tEntry.getValue();
			if (tInt != sMap.get(tCharacter)) {
				return tCharacter;
			}
		}
		return tChars[tChars.length - 1];
	
	}

}
